services:
  - type: web
    name: insurance-claims-app
    env: java
    plan: free
    runtime: docker
    region: Ohio

    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar

    envVars:
      - key: JAVA_VERSION
        value: 17
