services:
  - type: web
    name: insurance-claims-app
    env: docker
    rootDir: server
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: JAVA_OPTS
        value: "-Xmx512m -Xms256m"
      - key: SERVER_PORT
        value: 8080
