services:
  - type: web
    name: insurance-claims
    env: docker
    rootDir: server
    plan: free
    branch: main
    autoDeploy: true
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: default
