spring:
  datasource:
    url: jdbc:h2:mem:claimsdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none          # we are providing schema.sql ourselves
    show-sql: true
  sql:
    init:
      mode: always            # run sql file on startup
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8080
